### ISSUE TITLE
Amount in Worldpay.Sdk.Models.AbstractOrder is a int?

### ISSUE THREAD

**Issue by RemarkLima** [Worldpay/worldpay-lib-dotnet#10]
Hi,

I've just noticed that the amount in the class:
`Worldpay.Sdk.Models.AbstractOrder is a int?`

Is a type of `int?` - should this be a `decimal?`

When I change it to a decimal I get an error:

> Error: Error parsing json, please check json request

Any insight would be useful, as we do not always take whole integer amounts!

**Comment by RemarkLima** [comment]
Just realised that the int value is then converted to a decimal and just needs to be multiplied by 100.

**Comment by mothman1** [comment]
I'm looking at the same issue right now, but what does this mean? how could I pass a decimal amount?
