### ISSUE TITLE
CardRequest() is never used!?

### ISSUE THREAD

**Issue by cwjackso** [Worldpay/worldpay-lib-dotnet#2]
In the Create order sample project for .net 3.5+ the 'CardRequest' object  which is created on line 48 from the form submission is never used.

Am I missing something? Or is the code incomplete. I have tried to get a valid token using GetAuthService() and passing the 'CardRequest' object on my own implementation but I keep getting an invalid JSON error from the service.

Thanks

Carl

**Comment by ao** [comment]
You should use Worldpay.js to create the Token.
